language: generic
services:
  - docker 

env:
  matrix:
    - ROS_DISTRO="melodic"   PRERELEASE=true
    - ROS_DISTRO="melodic"   PRERELEASE=true OS_NAME=debian OS_CODE_NAME=stretch
install:
  - git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config  
script: 
  - .ci_config/travis.sh
