sudo: required
dist: trusty
language: generic

env:
  matrix:
    - ROS_DISTRO="jade" PRERELEASE=true
    - ROS_DISTRO="kinetic" PRERELEASE=true
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - .ci_config/travis.sh
