sudo: required 
dist: trusty 
language: generic 
env:
  matrix:
    - ROS_DISTRO="kinetic" ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO="kinetic" ROS_REPO=ros
    - ROS_DISTRO="lunar"   ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO="lunar"   ROS_REPO=ros
matrix:
  allow_failures:
    - env: ROS_DISTRO="jade" ROS_REPO=ros

install:
  - git clone --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config  
script: 
  - .ci_config/travis.sh
