joint_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  topic: "test"
  joints:
    - rig1_plate_joint
    - rig2_plate_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.5
    rig1_plate_joint: {trajectory: 0.1, goal: 0.1}
    rig2_plate_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  required_drive_mode: 7

joint_trajectory_pid_controller:
  type: position_controllers/JointTrajectoryController
  topic: "test"
  joints:
    - rig1_plate_joint
    - rig2_plate_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.5
    rig1_plate_joint: {trajectory: 0.1, goal: 0.1}
    rig2_plate_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  gains:
    rig1_plate_joint: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}
    rig2_plate_joint: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}
  required_drive_mode: 3

rig1_plate_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: rig1_plate_joint
  required_drive_mode: 1

rig1_plate_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: rig1_plate_joint
  required_drive_mode: 3

rig2_plate_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: rig2_plate_joint
  required_drive_mode: 1

rig2_plate_joint_velocity_controller:
  type: velocity_controllers/JointVelocityController
  joint: rig2_plate_joint
  required_drive_mode: 3

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
