master:
  node_id: 1
  driver: "ros2_canopen::LifecycleMasterDriver"
  package: "canopen_master_driver"

proxy_device_1:
  node_id: 2
  dcf: "simple.eds"
  dcf_path: "install/canopen_tests/share/canopen_tests/config/simple_lifecycle"
  driver: "ros2_canopen::LifecycleProxyDriver"
  package: "canopen_proxy_driver"

proxy_device_2:
  node_id: 3
  dcf: "simple.eds"
  dcf_path: "install/canopen_tests/share/canopen_tests/config/simple_lifecycle"
  driver: "ros2_canopen::LifecycleProxyDriver"
  package: "canopen_proxy_driver"