rig2_controller:
  type: position_controllers/JointTrajectoryController
  topic: "test"
  joints:
    - rig2_plate_joint
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.5
    rig2_plate_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10

rig1_joint_position_controller:
  type: position_controllers/JointPositionController
  joint: rig2_plate_joint

joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
